import {
  copyFileSync,
  existsSync,
  lstatSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  realpathSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'fs';
import { execFileSync } from 'node:child_process';
import { homedir } from 'os';
import { dirname, isAbsolute, join, relative, resolve } from 'path';
import { fileURLToPath } from 'url';
import { CODEX_UNSUPPORTED_HOOKS, codexRuntime } from '../core/runtimes/codex.js';
import { isOwnedHookEntry } from '../core/runtimes/types.js';

export const CODEX_TOOL_MATCHER = 'Write|Edit|MultiEdit|Bash|Agent|Task|task|apply_patch|exec_command|spawn_agent|wait_agent';
const BRAINBREW_MARKER = '<!-- Generated by brainbrew-devkit for Codex.';
const MANIFEST_RELATIVE_PATH = join('brainbrew', 'skills-manifest.json');

type CodexHook = {
  type: 'command';
  command: string;
  timeout: number;
};

type CodexHookEntry = {
  matcher: string;
  hooks: CodexHook[];
};

type CodexHooksFile = {
  hooks: Record<string, CodexHookEntry[]>;
};

type SkillKind = 'plugin-skill' | 'template-skill' | 'agent-role' | 'workflow-recipe';

type SkillSource = {
  skillName: string;
  sourcePath: string;
  kind: SkillKind;
  template?: string;
  rawName: string;
  skipped?: string;
};

type SkillProjection = {
  skillName: string;
  skillMarkdown: string;
  sourcePath: string;
  kind: SkillKind;
  references?: Array<{ relativePath: string; content: string }>;
};

type SkillManifestEntry = {
  skillName: string;
  source: string;
  kind: SkillKind;
  generatedAt: string;
};

type CodexPluginManifest = {
  agents?: string | Array<{ name?: string; path?: string; description?: string }>;
  commands?: string | Array<{ name?: string; path?: string; description?: string }>;
  skills?: string | Array<{ name?: string; path?: string; description?: string }>;
  mcpServers?: string | Record<string, unknown>;
  hooks?: string | Record<string, unknown>;
  apps?: string | Array<{ name?: string; path?: string }>;
  assets?: string | Array<string | { path?: string }>;
};

type CodexPaths = {
  codexHome: string;
  configFile: string;
  hooksFile: string;
  skillsDir: string;
};

export function codexCommand(args: string[], flags: Record<string, string>): void {
  const sub = args[0];

  switch (sub) {
    case 'init':
      return codexInit(flags);
    case 'sync-brainbrew-skills':
      return codexSyncBrainbrewSkills(flags);
    case 'status':
      return codexStatus(flags);
    default:
      printHelp();
  }
}

function printHelp(): void {
  console.log(`Usage: brainbrew codex <command> [options]

Commands:
  init                   Install Codex hook entries
  sync-brainbrew-skills  Sync BrainBrew-owned workflow, role, and helper skills into Codex
  status                 Check Codex runtime support

Options:
  --plugin-root <path>   Override plugin root
  --home <path>          Override Codex home directory for tests
  --project-root <path>  Override project root for BrainBrew state`);
}

function codexPaths(flags: Record<string, string>): CodexPaths {
  const codexHome = flags.home ? resolve(flags.home) : codexRuntime.homeDir;
  return {
    codexHome,
    configFile: join(codexHome, 'config.toml'),
    hooksFile: join(codexHome, 'hooks.json'),
    skillsDir: join(codexHome, 'skills'),
  };
}

function projectRoot(flags: Record<string, string>): string {
  return flags['project-root'] ? resolve(flags['project-root']) : process.cwd();
}

function codexInit(flags: Record<string, string>): void {
  const paths = codexPaths(flags);
  const pluginRoot = resolvePluginRoot(flags);
  const runnerPath = resolveRunnerPath(pluginRoot);

  if (!existsSync(runnerPath)) {
    console.error(`Codex runner not found at ${runnerPath}. Run npm run build before brainbrew codex init.`);
    process.exit(1);
  }

  mkdirSync(paths.codexHome, { recursive: true });
  if (!existsSync(paths.configFile)) {
    console.log(`Warning: ${paths.configFile} not found`);
  } else {
    const config = readFileSync(paths.configFile, 'utf-8');
    if (!hasTomlBoolean(config, 'hooks', true)) {
      console.log('Warning: Codex config does not contain hooks = true');
    }
    if (hasTomlBoolean(config, 'plugin_hooks', false)) {
      console.log('plugin_hooks = false is acceptable for BrainBrew Codex setup');
    }
  }

  const existing = readCodexHooksFile(paths.hooksFile);
  const merged = mergeCodexHooks(existing, pluginRoot);
  writeCodexHooksFile(paths.hooksFile, merged);

  try {
    mkdirSync(join(projectRoot(flags), codexRuntime.projectMemoryDirName), { recursive: true });
  } catch {}

  console.log(`Codex hooks installed: ${codexRuntime.supportedHooks.length}/${codexRuntime.supportedHooks.length}`);
  console.log(`Updated: ${paths.hooksFile}`);

  const registration = registerCodexMcpServer({ pluginRoot });
  console.log(`MCP registration: ${registration.message}`);
  if (registration.manualCommand) {
    console.log(`To register manually: ${registration.manualCommand}`);
  }
}

function codexSyncBrainbrewSkills(flags: Record<string, string>): void {
  const pluginRoot = resolvePluginRoot(flags);
  const paths = codexPaths(flags);
  const result = syncCodexSkills({ pluginRoot, codexHome: paths.codexHome, now: new Date() });
  console.log(`Installed/updated skills: ${result.installed.length}`);
  if (result.skipped.length) console.log(`Skipped skills: ${result.skipped.length}`);
  if (result.conflicts.length) console.log(`Conflicts preserved: ${result.conflicts.length}`);
}

function codexStatus(flags: Record<string, string>): void {
  const pluginRoot = tryResolvePluginRoot(flags);
  const paths = codexPaths(flags);
  const config = existsSync(paths.configFile) ? readFileSync(paths.configFile, 'utf-8') : '';
  const hooks = safeReadHooks(paths.hooksFile);
  const runnerPath = pluginRoot ? resolveRunnerPath(pluginRoot) : '';
  const brainbrewHooks = hooks ? countBrainbrewHooks(hooks) : 0;
  const unsupported = hooks ? Object.keys(hooks.hooks).filter(h => CODEX_UNSUPPORTED_HOOKS.includes(h as (typeof CODEX_UNSUPPORTED_HOOKS)[number])) : [];
  const manifest = readSkillManifest(join(paths.codexHome, MANIFEST_RELATIVE_PATH));
  const missingSkills = manifest.filter(entry => !existsSync(join(paths.skillsDir, entry.skillName, 'SKILL.md')));
  const pluginManifestPath = pluginRoot ? join(pluginRoot, codexRuntime.pluginManifestPath) : '';
  const pluginManifest = pluginManifestPath ? readCodexPluginManifest(pluginManifestPath) : null;
  const mcpStatus = pluginRoot ? getMcpStatus(pluginRoot, pluginManifest) : { declared: 0, packaged: false, missing: [] as string[] };
  const nativeSkillStatus = pluginRoot ? getNativeSkillStatus(pluginRoot, pluginManifest) : { count: 0, missing: [] as string[] };
  const commandStatus = pluginRoot ? getNativeDirectoryStatus(pluginRoot, pluginManifest?.commands, '.md') : { count: 0, missing: [] as string[] };
  const agentStatus = pluginRoot ? getNativeDirectoryStatus(pluginRoot, pluginManifest?.agents) : { count: 0, missing: [] as string[] };
  const assetStatus = pluginRoot ? getNativeAssetStatus(pluginRoot, pluginManifest) : { count: 0, missing: [] as string[] };
  const appStatus = pluginRoot ? getNativeAppStatus(pluginRoot, pluginManifest) : { count: 0, missing: [] as string[] };
  const projectState = getProjectStateStatus(projectRoot(flags));

  console.log('Codex runtime status');
  console.log(`Config: ${existsSync(paths.configFile) ? 'present' : 'missing'} (${paths.configFile})`);
  console.log(`hooks = true: ${config ? (hasTomlBoolean(config, 'hooks', true) ? 'yes' : 'no') : 'unknown'}`);
  console.log(`plugin_hooks: ${config ? readTomlBooleanStatus(config, 'plugin_hooks') : 'unknown'}`);
  console.log(`Hooks file: ${existsSync(paths.hooksFile) ? 'present' : 'missing'} (${paths.hooksFile})`);
  console.log(`BrainBrew hooks: ${brainbrewHooks}/${codexRuntime.supportedHooks.length}`);
  console.log(`Unsupported hooks: ${unsupported.length ? unsupported.join(', ') : 'none'}`);
  console.log(`Runner: ${runnerPath && existsSync(runnerPath) ? 'present' : 'missing'}${runnerPath ? ` (${runnerPath})` : ''}`);
  console.log(`Plugin manifest: ${pluginManifest ? 'present' : 'missing'}${pluginManifestPath ? ` (${pluginManifestPath})` : ''}`);
  console.log(`Plugin commands: ${formatNativeStatus(commandStatus.count, commandStatus.missing)}`);
  console.log(`Plugin agents: ${formatNativeStatus(agentStatus.count, agentStatus.missing)}`);
  console.log(`Plugin-native skills: ${formatNativeStatus(nativeSkillStatus.count, nativeSkillStatus.missing)}`);
  console.log(`Plugin MCP declaration: ${formatMcpDeclarationStatus(pluginManifest)}`);
  console.log(`Packaged MCP server: ${formatPackagedMcpStatus(mcpStatus)}`);
  console.log(`Packaged hook template: ${pluginRoot ? formatNativeStatus(1, getManifestPathMissing(pluginRoot, `./${relative(resolve(pluginRoot, codexRuntime.pluginManifestPath.split('/.codex-plugin/')[0]), join(pluginRoot, codexRuntime.hookTemplatePath))}`)) : 'none declared'}`);
  console.log(`Plugin apps: ${formatNativeStatus(appStatus.count, appStatus.missing)}`);
  console.log(`Plugin assets: ${formatNativeStatus(assetStatus.count, assetStatus.missing)}`);
  console.log(`BrainBrew skills: ${manifest.length}`);
  console.log(`Stale or missing generated skills: ${missingSkills.length}`);
  console.log(`Project state: ${projectState}`);
  console.log(`MCP registration: ${describeMcpRegistration(pluginRoot)}`);
}

function describeMcpRegistration(pluginRoot: string | null): string {
  if (!pluginRoot) return 'unknown (plugin root not resolved)';
  const serverPath = locatePackagedCodexMcpServer(pluginRoot);
  const runner = defaultCodexCliRunner();
  if (!runner.which('codex')) {
    return 'unknown (codex CLI not on PATH)';
  }
  if (runner.get('brainbrew')) {
    return 'brainbrew registered';
  }
  const manual = serverPath
    ? `codex mcp add brainbrew -- node ${serverPath}`
    : 'codex mcp add brainbrew -- node <path-to-mcp-server.cjs>';
  return `not registered — run brainbrew codex init or ${manual}`;
}

export function quoteCommandPath(path: string): string {
  return `'${path.replace(/'/g, `'\\''`)}'`;
}

export function buildCodexHookEntry(pluginRoot: string, eventName: string): CodexHookEntry {
  const runnerPath = resolveRunnerPath(pluginRoot);
  return {
    matcher: eventName === 'PreToolUse' || eventName === 'PostToolUse' ? CODEX_TOOL_MATCHER : '.*',
    hooks: [
      {
        type: 'command',
        command: `node ${quoteCommandPath(runnerPath)} ${eventName}`,
        timeout: eventName === 'PostToolUse' ? 60 : 30,
      },
    ],
  };
}

export function createCodexHooks(pluginRoot: string): CodexHooksFile {
  const hooks: Record<string, CodexHookEntry[]> = {};
  for (const eventName of codexRuntime.supportedHooks) {
    hooks[eventName] = [buildCodexHookEntry(pluginRoot, eventName)];
  }
  return { hooks };
}

export function mergeCodexHooks(existing: CodexHooksFile, pluginRoot: string): CodexHooksFile {
  const merged: CodexHooksFile = { hooks: { ...(existing.hooks ?? {}) } };
  for (const eventName of codexRuntime.supportedHooks) {
    const entries = Array.isArray(merged.hooks[eventName]) ? merged.hooks[eventName] : [];
    merged.hooks[eventName] = [
      ...entries.filter(entry => !isOwnedHookEntry(entry, codexRuntime.ownedHookId, codexRuntime.runnerScriptName)),
      buildCodexHookEntry(pluginRoot, eventName),
    ];
  }
  return merged;
}

export function readCodexHooksFile(hooksFile: string): CodexHooksFile {
  if (!existsSync(hooksFile)) return { hooks: {} };
  try {
    const parsed = JSON.parse(readFileSync(hooksFile, 'utf-8')) as unknown;
    if (!parsed || typeof parsed !== 'object' || !('hooks' in parsed) || typeof (parsed as { hooks: unknown }).hooks !== 'object') {
      throw new Error('Expected an object with a hooks property');
    }
    return parsed as CodexHooksFile;
  } catch (err) {
    throw new Error(`Invalid Codex hooks JSON at ${hooksFile}: ${(err as Error).message}`);
  }
}

export function writeCodexHooksFile(hooksFile: string, hooks: CodexHooksFile): void {
  mkdirSync(dirname(hooksFile), { recursive: true });
  if (existsSync(hooksFile)) {
    copyFileSync(hooksFile, `${hooksFile}.bak`);
  }
  writeFileSync(hooksFile, JSON.stringify(hooks, null, 2) + '\n');
}

export function collectCodexSkillSources(pluginRoot: string): SkillSource[] {
  const pluginDir = join(pluginRoot, 'plugin');
  const candidates: SkillSource[] = [];

  const codexPluginSkillsDir = join(pluginRoot, 'plugin-codex', 'skills');
  if (existsSync(codexPluginSkillsDir)) {
    for (const name of sortedSkillDirs(codexPluginSkillsDir)) {
      candidates.push({
        skillName: name,
        rawName: name,
        sourcePath: join(codexPluginSkillsDir, name),
        kind: 'plugin-skill',
      });
    }
  }

  const pluginSkillsDir = join(pluginDir, 'skills');
  if (existsSync(pluginSkillsDir)) {
    const existingSkillNames = new Set(candidates.map(candidate => candidate.skillName));
    for (const name of sortedSkillDirs(pluginSkillsDir)) {
      if (existingSkillNames.has(name)) continue;
      candidates.push({
        skillName: name,
        rawName: name,
        sourcePath: join(pluginSkillsDir, name),
        kind: 'plugin-skill',
      });
    }
  }

  const templatesDir = join(pluginDir, 'config', 'templates');
  const templates = existsSync(templatesDir)
    ? readdirSync(templatesDir).filter(f => statSync(join(templatesDir, f)).isDirectory()).sort()
    : [];

  const templateSkillRawNames = new Map<string, number>();
  const templateAgentRawNames = new Map<string, number>();
  for (const template of templates) {
    for (const name of sortedDirs(join(templatesDir, template, 'skills'))) {
      templateSkillRawNames.set(name, (templateSkillRawNames.get(name) ?? 0) + 1);
    }
    for (const file of sortedFiles(join(templatesDir, template, 'agents'), '.md')) {
      const rawName = file.replace(/\.md$/, '');
      templateAgentRawNames.set(rawName, (templateAgentRawNames.get(rawName) ?? 0) + 1);
    }
  }

  for (const template of templates) {
    for (const name of sortedDirs(join(templatesDir, template, 'skills'))) {
      candidates.push({
        skillName: templateSkillRawNames.get(name)! > 1 ? `${template}-${name}` : name,
        rawName: name,
        sourcePath: join(templatesDir, template, 'skills', name),
        kind: 'template-skill',
        template,
      });
    }
    for (const file of sortedFiles(join(templatesDir, template, 'agents'), '.md')) {
      const rawName = file.replace(/\.md$/, '');
      candidates.push({
        skillName: templateAgentRawNames.get(rawName)! > 1 ? `${template}-${rawName}` : rawName,
        rawName,
        sourcePath: join(templatesDir, template, 'agents', file),
        kind: 'agent-role',
        template,
      });
    }
  }

  for (const yamlFile of sortedFiles(templatesDir, '.yaml')) {
    const template = yamlFile.replace(/\.yaml$/, '');
    candidates.push({
      skillName: `${template}-workflow`,
      rawName: template,
      sourcePath: join(templatesDir, yamlFile),
      kind: 'workflow-recipe',
      template,
    });
  }

  return candidates.filter(source => isCodexCompatible(source));
}

export function createCodexSkillProjection(source: SkillSource): SkillProjection {
  const sourceContent = readSourceText(source);
  const rel = normalizedSourcePath(source.sourcePath);
  const marker = `${BRAINBREW_MARKER} Source: ${rel}. Kind: ${source.kind}. -->`;

  if (source.kind === 'workflow-recipe') {
    return {
      skillName: source.skillName,
      sourcePath: source.sourcePath,
      kind: source.kind,
      skillMarkdown: `---
name: ${source.skillName}
description: Use the ${source.rawName} BrainBrew workflow as Codex recipe guidance.
---

${marker}

# ${source.rawName} Workflow Recipe

This BrainBrew YAML is recipe and guidance only for Codex. It is not an executable state machine.

Use the referenced workflow to plan role handoffs, review gates, and expected deliverables. Do not assume Codex will automatically execute chain routing.

See \`references/${source.rawName}.yaml\` for the original recipe.
`,
      references: [{ relativePath: `${source.rawName}.yaml`, content: sourceContent }],
    };
  }

  if (source.kind === 'agent-role') {
    const body = stripFrontmatter(sourceContent).trim();
    return {
      skillName: source.skillName,
      sourcePath: source.sourcePath,
      kind: source.kind,
      skillMarkdown: `---
name: ${source.skillName}
description: Codex role guidance converted from the ${source.rawName} BrainBrew template agent.
---

${marker}

# ${source.rawName} Role

Use this as role guidance in Codex. It describes responsibilities, review criteria, and expected output. It does not spawn a Claude subagent or enforce an automatic chain step.

${transformCodexText(body)}
`,
    };
  }

  const skillFile = join(source.sourcePath, 'SKILL.md');
  const body = transformCodexText(readFileSync(skillFile, 'utf-8'));
  return {
    skillName: source.skillName,
    sourcePath: source.sourcePath,
    kind: source.kind,
    skillMarkdown: insertMarkerAfterFrontmatter(body, marker),
  };
}

export function syncCodexSkills(options: { pluginRoot: string; codexHome: string; now: Date }): {
  installed: string[];
  skipped: Array<{ skillName: string; reason: string }>;
  conflicts: Array<{ skillName: string; path: string }>;
} {
  const skillsDir = join(options.codexHome, 'skills');
  const manifestPath = join(options.codexHome, MANIFEST_RELATIVE_PATH);
  const manifest = readSkillManifest(manifestPath);
  const manifestNames = new Set(manifest.map(entry => entry.skillName));
  const sources = collectCodexSkillSources(options.pluginRoot);
  const installed: string[] = [];
  const skipped: Array<{ skillName: string; reason: string }> = [];
  const conflicts: Array<{ skillName: string; path: string }> = [];
  const nextManifest: SkillManifestEntry[] = [];

  mkdirSync(skillsDir, { recursive: true });

  for (const source of sources) {
    const projection = createCodexSkillProjection(source);
    const destDir = join(skillsDir, projection.skillName);
    const destSkill = join(destDir, 'SKILL.md');
    const hasManifestEntry = manifestNames.has(projection.skillName);
    const hasMarker = isBrainbrewSkillDir(destDir);
    const existingOwned = existsSync(destDir) && hasMarker;

    if (existsSync(destDir) && (!existingOwned || !hasManifestEntry)) {
      conflicts.push({ skillName: projection.skillName, path: destDir });
      continue;
    }

    if (existsSync(destDir)) rmSync(destDir, { recursive: true, force: true });
    mkdirSync(destDir, { recursive: true });
    writeFileSync(destSkill, projection.skillMarkdown.endsWith('\n') ? projection.skillMarkdown : `${projection.skillMarkdown}\n`);

    if (source.kind === 'plugin-skill' || source.kind === 'template-skill') {
      copySupportingFiles(source.sourcePath, destDir);
    }

    if (projection.references?.length) {
      const refDir = join(destDir, 'references');
      mkdirSync(refDir, { recursive: true });
      for (const ref of projection.references) {
        writeFileSync(join(refDir, ref.relativePath), ref.content);
      }
    }

    installed.push(projection.skillName);
    nextManifest.push({
      skillName: projection.skillName,
      source: normalizedSourcePath(source.sourcePath),
      kind: projection.kind,
      generatedAt: options.now.toISOString(),
    });
  }

  mkdirSync(dirname(manifestPath), { recursive: true });
  writeFileSync(manifestPath, JSON.stringify({ skills: nextManifest }, null, 2) + '\n');
  return { installed, skipped, conflicts };
}

function resolvePluginRoot(flags: Record<string, string>): string {
  const root = tryResolvePluginRoot(flags);
  if (!root) {
    console.error('Unable to resolve BrainBrew plugin root. Use --plugin-root <path> or set BRAINBREW_PLUGIN_ROOT.');
    process.exit(1);
  }
  return root;
}

function tryResolvePluginRoot(flags: Record<string, string>): string | null {
  const explicit = flags['plugin-root'] || process.env.BRAINBREW_PLUGIN_ROOT;
  if (explicit) return resolve(explicit);

  let current = dirname(fileURLToPath(import.meta.url));
  for (let i = 0; i < 8; i++) {
    if (hasPluginRoot(current)) return current;
    const parent = dirname(current);
    if (parent === current) break;
    current = parent;
  }

  const cwd = process.cwd();
  if (hasPluginRoot(cwd) || existsSync(join(cwd, 'plugin'))) return cwd;
  return null;
}

function hasPluginRoot(root: string): boolean {
  return (
    existsSync(join(root, codexRuntime.pluginManifestPath)) ||
    existsSync(join(root, 'plugin', '.claude-plugin', 'plugin.json'))
  );
}

function resolveRunnerPath(pluginRoot: string): string {
  const codexRunner = join(pluginRoot, 'plugin-codex', 'scripts', codexRuntime.runnerScriptName);
  if (existsSync(codexRunner)) return codexRunner;
  return join(pluginRoot, 'plugin', 'scripts', codexRuntime.runnerScriptName);
}

function hasTomlBoolean(content: string, key: string, value: boolean): boolean {
  const pattern = new RegExp(`^\\s*${key}\\s*=\\s*${value ? 'true' : 'false'}\\s*(?:#.*)?$`, 'm');
  return pattern.test(content);
}

function readTomlBooleanStatus(content: string, key: string): string {
  if (hasTomlBoolean(content, key, true)) return 'true';
  if (hasTomlBoolean(content, key, false)) return 'false';
  return 'unset';
}

function safeReadHooks(hooksFile: string): CodexHooksFile | null {
  try {
    return readCodexHooksFile(hooksFile);
  } catch {
    return null;
  }
}

function countBrainbrewHooks(hooks: CodexHooksFile): number {
  let count = 0;
  for (const eventName of codexRuntime.supportedHooks) {
    const entries = hooks.hooks[eventName] ?? [];
    if (entries.some(entry => isOwnedHookEntry(entry, codexRuntime.ownedHookId, codexRuntime.runnerScriptName))) count++;
  }
  return count;
}

function readSkillManifest(manifestPath: string): SkillManifestEntry[] {
  if (!existsSync(manifestPath)) return [];
  try {
    const parsed = JSON.parse(readFileSync(manifestPath, 'utf-8')) as { skills?: SkillManifestEntry[] };
    return Array.isArray(parsed.skills) ? parsed.skills : [];
  } catch {
    return [];
  }
}

function readCodexPluginManifest(manifestPath: string): CodexPluginManifest | null {
  if (!existsSync(manifestPath)) return null;
  try {
    const parsed = JSON.parse(readFileSync(manifestPath, 'utf-8')) as unknown;
    return parsed && typeof parsed === 'object' ? parsed as CodexPluginManifest : null;
  } catch {
    return null;
  }
}

function getNativeSkillStatus(pluginRoot: string, manifest: CodexPluginManifest | null): { count: number; missing: string[] } {
  return getNativeDirectoryStatus(pluginRoot, manifest?.skills, 'SKILL.md');
}

function getMcpStatus(pluginRoot: string, manifest: CodexPluginManifest | null): { declared: number; packaged: boolean; missing: string[] } {
  const manifestPathMissing = getManifestPathMissing(pluginRoot, manifest?.mcpServers);
  const mcpConfigPath = typeof manifest?.mcpServers === 'string' ? manifest.mcpServers : './.mcp.json';
  const mcpConfig = readCodexPluginManifest(resolvePluginPath(pluginRoot, mcpConfigPath));
  const configServers = mcpConfig?.mcpServers && typeof mcpConfig.mcpServers === 'object' && !Array.isArray(mcpConfig.mcpServers)
    ? Object.keys(mcpConfig.mcpServers)
    : [];
  const packagedServer = existsSync(join(pluginRoot, 'plugin-codex', 'mcp', 'mcp-server.cjs')) ||
    existsSync(join(pluginRoot, 'plugin', 'mcp', 'mcp-server.cjs'));
  return { declared: configServers.length, packaged: packagedServer, missing: manifestPathMissing };
}

function formatMcpDeclarationStatus(manifest: CodexPluginManifest | null): string {
  if (!manifest?.mcpServers) return 'none declared';
  if (typeof manifest.mcpServers === 'string') return 'declared by config file';
  const count = Object.keys(manifest.mcpServers).length;
  return formatNativeStatus(count, []);
}

function formatPackagedMcpStatus(status: { packaged: boolean; missing: string[] }): string {
  if (status.missing.length) return `present, ${status.missing.length} declaration path missing`;
  return status.packaged ? 'present' : 'missing';
}

function getNativeAppStatus(pluginRoot: string, manifest: CodexPluginManifest | null): { count: number; missing: string[] } {
  return getNativeDirectoryStatus(pluginRoot, manifest?.apps);
}

function getNativeAssetStatus(pluginRoot: string, manifest: CodexPluginManifest | null): { count: number; missing: string[] } {
  const assets = manifest?.assets;
  if (!assets) return { count: 0, missing: [] };
  if (typeof assets === 'string') {
    return { count: existsSync(resolvePluginPath(pluginRoot, assets)) ? 1 : 0, missing: getManifestPathMissing(pluginRoot, assets) };
  }
  const paths = assets
    .map(asset => typeof asset === 'string' ? asset : asset.path)
    .filter((path): path is string => typeof path === 'string' && path.length > 0);
  const missing = paths.filter(path => !existsSync(resolvePluginPath(pluginRoot, path)));
  return { count: paths.length, missing };
}

function getNativeDirectoryStatus(
  pluginRoot: string,
  declaration: string | Array<{ name?: string; path?: string; description?: string }> | undefined,
  extension?: string,
): { count: number; missing: string[] } {
  if (!declaration) return { count: 0, missing: [] };
  if (typeof declaration === 'string') {
    const target = resolvePluginPath(pluginRoot, declaration);
    if (!existsSync(target)) return { count: 0, missing: [declaration] };
    if (!statSync(target).isDirectory()) return { count: 1, missing: [] };
    return { count: countDeclaredEntries(target, extension), missing: [] };
  }
  const paths = declaration
    .map(item => item.path)
    .filter((path): path is string => typeof path === 'string' && path.length > 0);
  const missing = paths.filter(path => !existsSync(resolvePluginPath(pluginRoot, path)));
  return { count: declaration.length, missing };
}

function resolvePluginPath(pluginRoot: string, pluginRelativePath: string): string {
  if (isAbsolute(pluginRelativePath)) return join(pluginRoot, 'plugin', '__invalid_absolute_path__');
  const normalized = pluginRelativePath.replace(/^\.\//, '');
  const pluginDir = resolve(pluginRoot, codexRuntime.pluginManifestPath.split('/.codex-plugin/')[0]);
  const resolved = resolve(pluginDir, normalized);
  return resolved === pluginDir || resolved.startsWith(`${pluginDir}/`) ? resolved : join(pluginDir, '__invalid_relative_path__');
}

function getManifestPathMissing(pluginRoot: string, declaration: string | Record<string, unknown> | undefined): string[] {
  if (!declaration || typeof declaration !== 'string') return [];
  return existsSync(resolvePluginPath(pluginRoot, declaration)) ? [] : [declaration];
}

function countDeclaredEntries(dir: string, extension?: string): number {
  if (extension === 'SKILL.md') {
    return sortedFilesRecursive(dir, 'SKILL.md').length;
  }
  return sortedFilesRecursive(dir, extension).length;
}

function sortedFilesRecursive(dir: string, extension?: string): string[] {
  if (!existsSync(dir)) return [];
  const result: string[] = [];
  for (const name of readdirSync(dir).sort()) {
    const fullPath = join(dir, name);
    const stat = statSync(fullPath);
    if (stat.isDirectory()) {
      result.push(...sortedFilesRecursive(fullPath, extension));
    } else if (!extension || name.endsWith(extension)) {
      result.push(fullPath);
    }
  }
  return result;
}

function formatNativeStatus(count: number, missing: string[]): string {
  if (count === 0) return 'none declared';
  return missing.length ? `${count} declared, ${missing.length} missing` : `${count} declared, present`;
}

function getProjectStateStatus(cwd: string): string {
  const current = join(cwd, codexRuntime.projectMemoryDirName);
  const currentState = join(current, 'workflow-state.json');
  const legacy = join(cwd, '.codex', 'memory');
  const legacyState = join(legacy, 'workflow-state.json');
  if (existsSync(currentState)) return `present (${codexRuntime.projectMemoryDirName})`;
  if (existsSync(current)) return `initialized (${codexRuntime.projectMemoryDirName})`;
  if (existsSync(legacyState)) return 'legacy present (.codex/memory)';
  if (existsSync(legacy)) return 'legacy initialized (.codex/memory)';
  return `missing (${codexRuntime.projectMemoryDirName})`;
}

function sortedDirs(dir: string): string[] {
  if (!existsSync(dir)) return [];
  return readdirSync(dir).filter(name => statSync(join(dir, name)).isDirectory()).sort();
}

function sortedSkillDirs(dir: string): string[] {
  return sortedDirs(dir).filter(name => existsSync(join(dir, name, 'SKILL.md')));
}

function sortedFiles(dir: string, extension: string): string[] {
  if (!existsSync(dir)) return [];
  return readdirSync(dir).filter(name => name.endsWith(extension) && statSync(join(dir, name)).isFile()).sort();
}

function readSourceText(source: SkillSource): string {
  if (source.kind === 'workflow-recipe' || source.kind === 'agent-role') {
    return readFileSync(source.sourcePath, 'utf-8');
  }
  return readFileSync(join(source.sourcePath, 'SKILL.md'), 'utf-8');
}

function stripFrontmatter(content: string): string {
  if (!content.startsWith('---')) return content;
  const end = content.indexOf('\n---', 3);
  if (end === -1) return content;
  return content.slice(end + 4);
}

function insertMarkerAfterFrontmatter(content: string, marker: string): string {
  if (!content.startsWith('---')) return `${marker}\n${content}`;
  const end = content.indexOf('\n---', 3);
  if (end === -1) return `${marker}\n${content}`;
  const frontmatterEnd = end + 4;
  return `${content.slice(0, frontmatterEnd)}\n\n${marker}\n${content.slice(frontmatterEnd).replace(/^\n/, '')}`;
}

function transformCodexText(content: string): string {
  return content
    .replace(/\.claude\/skills/g, '~/.codex/skills')
    .replace(/\.claude\/agents/g, 'BrainBrew role skills')
    .replace(/Claude Code/g, 'Codex')
    .replace(/Claude/g, 'Codex');
}

function isCodexCompatible(source: SkillSource): boolean {
  const content = readSourceText(source);
  if (source.kind === 'workflow-recipe' || source.kind === 'agent-role') return true;
  const claudeOnly = [
    'SubagentStart',
    'SubagentStop',
    'SessionEnd',
    'TeamCreate',
    'Agent(subagent_type=',
    '.claude/hooks',
    'Claude plugin hook dispatch',
  ];
  return !claudeOnly.some(token => content.includes(token));
}

function isBrainbrewSkillDir(dir: string): boolean {
  const skillFile = join(dir, 'SKILL.md');
  if (!existsSync(skillFile)) return false;
  return readFileSync(skillFile, 'utf-8').includes(BRAINBREW_MARKER);
}

function copySupportingFiles(sourceDir: string, destDir: string): void {
  for (const item of readdirSync(sourceDir)) {
    if (item === 'SKILL.md') continue;
    copyRecursive(join(sourceDir, item), join(destDir, item), sourceDir);
  }
}

function copyRecursive(src: string, dest: string, sourceRoot: string): void {
  const lstat = lstatSync(src);
  if (lstat.isSymbolicLink()) return;
  const realSourceRoot = realpathSync(sourceRoot);
  const realSource = realpathSync(src);
  if (realSource !== realSourceRoot && !realSource.startsWith(`${realSourceRoot}/`)) return;
  const stat = statSync(src);
  if (stat.isDirectory()) {
    mkdirSync(dest, { recursive: true });
    for (const item of readdirSync(src)) copyRecursive(join(src, item), join(dest, item), sourceRoot);
    return;
  }
  copyFileSync(src, dest);
}

function normalizedSourcePath(sourcePath: string): string {
  const rel = relative(process.cwd(), sourcePath);
  return rel.startsWith('..') ? sourcePath : rel;
}

export type McpRegistrationStatus =
  | 'registered'
  | 'already-registered'
  | 'cli-missing'
  | 'failed'
  | 'no-server';

export type McpRegistrationResult = {
  status: McpRegistrationStatus;
  message: string;
  manualCommand?: string;
};

export type CodexCliRunner = {
  which: (cmd: string) => boolean;
  get: (name: string) => boolean;
  add: (args: string[]) => void;
};

export function locatePackagedCodexMcpServer(pluginRoot: string): string | null {
  const codexPath = join(pluginRoot, 'plugin-codex', 'mcp', 'mcp-server.cjs');
  if (existsSync(codexPath)) return codexPath;
  const fallback = join(pluginRoot, 'plugin', 'mcp', 'mcp-server.cjs');
  if (existsSync(fallback)) return fallback;
  return null;
}

export function buildCodexMcpAddArgs(name: string, serverPath: string): string[] {
  return ['mcp', 'add', name, '--', 'node', serverPath];
}

function defaultCodexCliRunner(): CodexCliRunner {
  return {
    which: () => {
      try {
        execFileSync('codex', ['--version'], { stdio: 'ignore' });
        return true;
      } catch {
        return false;
      }
    },
    get: name => {
      try {
        execFileSync('codex', ['mcp', 'get', name], { stdio: 'ignore' });
        return true;
      } catch {
        return false;
      }
    },
    add: args => {
      execFileSync('codex', args, { stdio: 'pipe' });
    },
  };
}

export function registerCodexMcpServer(options: {
  pluginRoot: string;
  name?: string;
  runner?: CodexCliRunner;
}): McpRegistrationResult {
  const name = options.name ?? 'brainbrew';
  const serverPath = locatePackagedCodexMcpServer(options.pluginRoot);
  if (!serverPath) {
    return {
      status: 'no-server',
      message: 'Packaged Codex MCP server not found in plugin tree',
    };
  }

  const runner = options.runner ?? defaultCodexCliRunner();
  const manualCommand = `codex mcp add ${name} -- node ${serverPath}`;

  if (!runner.which('codex')) {
    return {
      status: 'cli-missing',
      message: 'codex CLI not on PATH; register the MCP server manually',
      manualCommand,
    };
  }

  if (runner.get(name)) {
    return {
      status: 'already-registered',
      message: `${name} MCP server already registered`,
    };
  }

  try {
    runner.add(buildCodexMcpAddArgs(name, serverPath));
    return {
      status: 'registered',
      message: `Registered ${name} MCP server with codex (${serverPath})`,
    };
  } catch (err) {
    return {
      status: 'failed',
      message: `Failed to register ${name} MCP server: ${(err as Error).message}`,
      manualCommand,
    };
  }
}
